local research = {}
research[0] = "automation"
research[1] = "electronics"
research[2] = "fast-inserter"
research[3] = "logistic-science-pack"
research[4] = "steel-processing"
research[5] = "steel-axe"
research[6] = "automation-2"
research[7] = "lab-research-speed-1"
research[8] = "lab-research-speed-2"
research[9] = "advanced-material-processing"
research[10] = "engine"
research[11] = "fluid-handling"
research[12] = "oil-processing"
research[13] = "sulfur-processing"
research[14] = "battery"
research[15] = "plastics"
research[16] = "advanced-electronics"
research[17] = "chemical-science-pack"
research[18] = "modules"
research[19] = "productivity-module-1"
research[20] = "circuit-network"
research[21] = "speed-module-1"
research[22] = "concrete"
research[23] = "stack-inserter"
research[24] = "logistics-2"
research[25] = "railway"
research[26] = "flamables"
research[27] = "advanced-oil-processing"
research[28] = "lubricant"
research[29] = "electric-engine"
research[30] = "robotics"
research[31] = "lab-research-speed-3"
research[32] = "lab-research-speed-4"
research[33] = "rocket-fuel"
research[34] = "advanced-electronics-2"
research[35] = "low-density-structure"
research[36] = "advanced-material-processing-2"
research[37] = "production-science-pack"
research[38] = "utility-science-pack"
research[39] = "productivity-module-2"
research[40] = "speed-module-2"
research[41] = "effect-transmission"
research[42] = "productivity-module-3"
research[43] = "speed-module-3"
research[44] = "rocket-control-unit"
research[45] = "rocket-silo"




return research